- src/Grid/GridToolbar.js
- test/Grid.spec.js
- test/GridToolbar.spec.js
* Added base unit testing cases
> Issue13 unit testing

- src/Grid/Grid.js
- src/Grid/GridToolbar.js
- src/Grid/RemoteDataSource.js
* Added printing functionality
> Issue07 print records

- src/Grid/Grid.js
- src/Grid/Paginator.js
- src/Grid/RemoteDataSource.js
- src/Grid/TablePaginationActions.js
- test/Grid.spec.js
Added a message that is shown when no records were found
Eliminated some styles of the paginator 
Fixed a bug when reloading page
> Show message when no records were found

- example/src/main.js
- src/Grid/RemoteDataSource.js
- src/Util/index.js
* Fixed column structure
* Fixed propType checking in `RemoteDataSource`
> Issue47 wrong column structure

- src/Grid/DateInput.js
- src/Grid/DialogContent.js
- src/Grid/DialogDropdown.js
- src/Grid/DialogInput.js
- src/Grid/Dropdown.js
- src/Grid/Grid.js
- src/Grid/GridHeader.js
- src/Grid/GridToolbar.js
- src/Grid/Paginator.js
- src/Grid/RemoteDataSource.js
- src/Grid/TextInput.js
Apply button is now disabled when the filter is none
Key press handler was added to the input
Page Size Bug Fixed
Bug fixed in search
> Deactivate apply button when the filter is none

- test/Grid.spec.js
* I added a new unit test to check if paginator exists when `showTopPager` prop is set as true
> Unit test for top pager

- src/Grid/Column.ts
- src/Grid/Grid.tsx
- src/Grid/GridHeader.tsx
I created a file named column where I created 2 enums, one for DataType and the other for SortDirection, also I changed Grid and GridHeader to use these enums.
> Changed DataType and SortDirection to Enum

- .travis.yml
- appveyor.yml
- gulpfile.js
- package.json
* Set up AppVeyor
* Set up Coveralls
> Issue78 Add AppVeyor

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (string). Case: `Not Equals`.
> Issue98-Unit test: Column string (case: Not Equals)

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (string). Case: `None`.
> Issue100-Unit test: Column string (case: None) 

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (string). Case: `Starts With`.
> Issue103-Unit test: Column string (case: Starts With)

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (string). Case: `Not Starts With`.
> Issue106-Unit test: Column string (case: Not Starts With)

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (string). Case: `Ends With`.
> Issue108-Unit test: Column string (case: Ends With) 

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (date). Case: `Equals`
> Issue115-Unit test: Column date (case: Equals)

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (date). Case: `Between`.
> Issue115-Unit test: Column date (case: Between)

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (date). Case: `>=`.
> Issue119-Unit test: Column date (case: Greather than Equals) 

- src/DataGrid/DialogDropdown.tsx
- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (date). Case: `>`.
> Issue121-Unit test: Column date (case: Greather than) 

- src/DataGrid/ColumnModel.ts
- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (date). Case: `<=`
> Issue127-Unit test: Column date (case: Less than or Equals to)

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Unit test added for column filtering (date). Case: `<`
> Issue130-Unit test: Column date (case: Less Than) 

- test/LocalDataSource.spec.tsx
- test/utils/LocalDataSourceMocks.ts
Missing unit test added for column filtering (date). Case: `Not Contains`
> Issue130-Unit test: Column date (case: Not Contains)

- test/LocalDataSource.spec.tsx
- test/utils/columns.ts
Unit test added for column with aggregate function (`Average`)
> Issue134-Unit test: Aggregate function (Average)

- test/LocalDataSource.spec.tsx
- test/utils/columns.ts
Unit test added for column with aggregate function (`Sum`)
> Issue136-Unit test: Aggregate function (Sum)

- package.json
- test/LocalDataSource.spec.tsx
Unit test added for column with aggregate function (`Min`)
> Issue134-Unit test: Aggregate function (Min)

- test/LocalDataSource.spec.tsx
- test/utils/columns.ts
Unit test added for column with aggregate function (`Distinct Count`)
> Issue141-Unit test: Aggregate function (Distinct Count) 

- test/LocalDataSource.spec.tsx
Unit test added for column with aggregate function (`Count`)
> Issue134-Unit test: Aggregate function (Count) 

- test/GridToolbar.spec.tsx
> Unit testing: GridToolbar 

- test/GridHeader.spec.tsx
* Add basic unit tests to check if `<GridHeader />` is rendering properly its inner components
* (work in progress...)
> Issue157-Unit testing: GridHeader

- package.json
- test/GridToolbar.spec.tsx
* `webpack.config.js` was added to exclude it in Coveralls
> Issue162-Coverage clean-up

- test/GridToolbar.spec.tsx
* The unit test related to `searchText` was fixed.
* Unit tests related to `printTable()` were updated and added.
> Issue-169: Update spec for <GridToolbar /> component

- gulpfile.js
- package.json
- test/DataGrid.spec.tsx
- test/GridHeader.spec.tsx
- test/GridToolbar.spec.tsx
- test/LocalDataSource.spec.tsx
- test/RemoteDataSource.spec.tsx
- test/TablePaginationActions.spec.tsx
- test/setupTest.js
* Updating test to be used with jest
* jest configuration added
> Issue174 test to jest

- README.md
- sample/src/CustomLayoutDataGrid.tsx
* change Math.round to Math.ceil for numbers with decimal before dot (#238)
* Updating readme and sample (#239)
> Issue#231_paginationBug (#240)

- src/DataGrid/DialogModal.tsx
There's no exist a "handleClose" action. needs to use the setFilter(clearFilterPatch) insted to clean the anchorElenFilter
> fix the problem

- src/Implementations/DataGridWithRemoteDataSource.tsx
Added prop to be able to use customs body in this DataGridWithRemoteDataSource
> Added bodyRenderer prop

- package-lock.json
- package.json
- src/DataGrid/DataGrid.tsx
- src/DataGrid/DataGridCard.tsx
- src/DataGrid/GridToolbar.tsx
- src/DataGrid/Paginator.tsx
- src/DataGrid/index.ts
> Issue321 responsive grid

- sample/src/localDataGrid.tsx
- src/DataGrid/DataGrid.tsx
- src/DataGrid/DataGridCard.tsx
- src/DataGrid/DataGridTable.tsx
- src/DataGrid/GridBody.tsx
- src/DataGrid/GridHeader.tsx
- src/DataGridInterfaces/IDataGridApi.ts
- src/DataGridInterfaces/IDataGridConfig.ts
- src/DataGridInterfaces/IDataGridState.ts
- src/Filtering/DialogInput.tsx
- src/Filtering/DialogModal.tsx
- src/Filtering/SearchTextInput.tsx
- src/Hooks/useDataGrid.ts
- src/Pagination/AdvancePaginationActions.tsx
- src/Pagination/Paginator.tsx
- src/Toolbar/ExportButton.tsx
- src/Toolbar/GridToolbar.tsx
- src/Toolbar/ToolbarOptions.ts
On this change I tried to reduce the amount of "any" all around.
We do require some any for data and aggregates since they don't have a specific type, in the future we may find a way to deal with it. 
Fixed some possible bugs thanks to type-safety.
> Better usage of types

- src/DataGrid/DataGrid.tsx
> [FIX] Removed children from mobile toolbar

- src/Toolbar/GridToolbarFunctions.ts
Function to export/print records was not handling invisible columns properly.
> [FIX-407] Fixed function to export rows

- package-lock.json
- sample/src/ColumnFeatures/ColumnFeatures.tsx
- sample/src/ColumnFeatures/ModifyingColumns.tsx
- sample/src/main.tsx
- src/Hooks/useDataGrid.ts
- tslint.json
Tubular was not being aware of changes on the underlying columns. I just added that ability so that the columns can be modified and the changes will be reflected on the grid.
Please take a look at ModifyingColumns.tsx for a working sample.
BTW, this was not related to NullStorage.
> [FIX] Adding ability to change columns at runtime

- src/DataGrid/DataGrid.tsx
- src/DataGrid/DataGridCard.tsx
- src/DataGrid/DataGridTable.tsx
- src/DataGrid/GridBody.tsx
- src/DataGrid/MobileDataGridTable.tsx
- src/DataGrid/NoDataRow.tsx
> Issue417 improve data grid

- package.json
- src/TbList/TbList.tsx
Fixed TbList component problem due to latest changes.
> Fixed TbList component

- src/Filtering/DialogModal.tsx
> Fixes filtering issue due to wrong case when handling filter change

- src/Toolbar/GridToolbar.tsx
- src/Toolbar/ToolbarOptions.ts
This PR adds the ability to add a title to the top left corner of the table, it's a nice fill for the whitespace
> Add support for table title in toolbar

- README.md
update in docs according to new method for create column also code sandbox link are changed to latest to reflect new updated methods
> Documentation change in readme file according to new updates

- src/DataGrid/FeaturesDrawer.tsx
- src/Filtering/FilterControl.tsx
- src/Filtering/FiltersContainer.tsx
- src/Filtering/StandardFilterEditor.tsx
- src/Filtering/StringFilter.tsx
- src/Filtering/utils.tsx
* Make sure that onEnter handler is defined before attempting to call it
* Pass onApplyClick down to the TextArea key handler
> Fix enter key crash in filters

- src/Pagination/AdvancePaginationActions.tsx
* When there are no records lastPage is set to -1 but page is 0
> Fix next buttons with no records found
